# .pre-commit-config.yaml

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Update to the latest stable version if needed
    hooks:
      - id: black
        name: Black
        entry: black
        language: system
        types: [python]
        args: [--line-length=88]